//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magenic.Manpower.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MagenicManpowerRecruitmentEntities : DbContext
    {
        public MagenicManpowerRecruitmentEntities()
            : base("name=MagenicManpowerRecruitmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicantLevel> ApplicantLevels { get; set; }
        public virtual DbSet<MagenicRegion> MagenicRegions { get; set; }
        public virtual DbSet<ManpowerRequest> ManpowerRequests { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<PrimarySkill> PrimarySkills { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Technology> Technologies { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ReferenceNumber> ReferenceNumbers { get; set; }
        public virtual DbSet<Applicant> Applicants { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<HrDashboardView> HrDashboardViews { get; set; }
    }
}
