//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magenic.Manpower.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManpowerRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManpowerRequest()
        {
            this.ReferenceNumbers = new HashSet<ReferenceNumber>();
            this.Technologies = new HashSet<Technology>();
        }
    
        public int Id { get; set; }
        public string ProjectName { get; set; }
        public int PrimarySkillID { get; set; }
        public int RegionID { get; set; }
        public int DesiredApplicantLevelID { get; set; }
        public int NumberOfHires { get; set; }
        public System.DateTime ProjectedStartDate { get; set; }
        public string JobDescription { get; set; }
        public int RequestedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public int ProjectId { get; set; }
        public bool IsForReplacement { get; set; }
        public bool IsForAdditionalResource { get; set; }
        public bool IsChangeRequest { get; set; }
    
        public virtual ApplicantLevel ApplicantLevel { get; set; }
        public virtual MagenicRegion MagenicRegion { get; set; }
        public virtual PrimarySkill PrimarySkill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferenceNumber> ReferenceNumbers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Technology> Technologies { get; set; }
        public virtual Project Project { get; set; }
    }
}
