//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magenic.Manpower.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceNumber
    {
        public int Id { get; set; }
        public string ReferenceString { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public int ManpowerRequestId { get; set; }
        public int StatusID { get; set; }
        public int LevelId { get; set; }
    
        public virtual ManpowerRequest ManpowerRequest { get; set; }
        public virtual Status Status { get; set; }
        public virtual ApplicantLevel ApplicantLevel { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
